name: caviare_flutter_colorpicker
description: 一个Material风格GridView形式的颜色选择器。
version: 1.0.2
homepage: https://github.com/ilovefish/caviare_flutter_colorpicker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
